### ISSUE TITLE
Feed with thumbnails; display error

### ISSUE THREAD

**Issue by idontveapc** [lidary-byte/flutter_rss_reader#2]
This is what showed (gray colour):
![ResizedImage_2024-03-28_14-24-46_2882](https://github.com/lidary-byte/flutter_rss_reader/assets/122597295/ea78ac6d-62f4-465c-9b24-aaf6b125dff4)

But you when the gray area tap; you can read articles:
![ResizedImage_2024-03-28_14-24-58_1159](https://github.com/lidary-byte/flutter_rss_reader/assets/122597295/79073148-2019-41e7-8c6f-670dd005b70b)

**Comment by lidary-byte** [comment]
Please provide the rss

**Comment by lidary-byte** [comment]
Fixed [v0.0.6](https://github.com/lidary-byte/flutter_rss_reader/releases)
